#!/bin/sh
systemctl stop shadowsocks-libev-server@config.service 
systemctl stop shadowsocks-libev-server
systemctl stop shadowsocks-libev
systemctl stop shadowsocks-libev-server@con1861.service 
systemctl stop shadowsocks-libev-server@con1862.service 
systemctl stop shadowsocks-libev-server@con1863.service 
systemctl stop shadowsocks-libev-server@con1864.service 
systemctl stop shadowsocks-libev-server@con1865.service 
systemctl stop shadowsocks-libev-server@con1866.service 
systemctl stop shadowsocks-libev-server@con1867.service 
systemctl stop shadowsocks-libev-server@con1868.service 
systemctl stop shadowsocks-libev-server@con1871.service 
systemctl stop shadowsocks-libev-server@con1872.service 
systemctl stop shadowsocks-libev-server@con1873.service 
systemctl stop shadowsocks-libev-server@con1874.service 
systemctl stop shadowsocks-libev-server@con1875.service 
systemctl stop shadowsocks-libev-server@con1876.service 
systemctl stop shadowsocks-libev-server@con1877.service 
systemctl stop shadowsocks-libev-server@con1878.service 
systemctl stop shadowsocks-libev-server@con1879.service 
